version: '3.8'

x-placement: &local-placement
  placement:
    constraints:
      - node.labels.pastvu.pastvu-data == true
x-defaults: &app-default
  image: pastvu/backend:${TAG?ERR}
  configs:
    - config.js

services:

  fileserver:
    deploy: *local-placement
    image: pastvu/fileserver:${TAG_FILESERVER?ERR}
    networks:
      - frontend
    volumes:
      - store:/store:ro
      - sitemap:/sitemap:ro

  frontend_ru:
    image: pastvu/frontend:${TAG?ERR}

  frontend_en:
    image: pastvu/frontend:${TAG_EN?ERR}

  app_primary:
    << : *app-default 
    networks:
      - backend
    environment:
      - PRIMARY=true
      - DOMAIN
      - PROTOCOL
    deploy:
      << : *local-placement
      mode: global

  app_ru:
    << : *app-default
    deploy: *local-placement
    environment:
      - DOMAIN
      - PROTOCOL
    networks:
      - frontend
      - backend
    volumes:
      - store:/store

  app_en:
    << : *app-default
    deploy: *local-placement
    image: pastvu/backend:${TAG_EN?ERR}
    networks:
      - frontend
      - backend
    environment:
      - DOMAIN
      - PROTOCOL
      - LANG=en
    volumes:
      - store:/store

  notifier_ru:
    << : *app-default 
    networks:
      - backend
    environment:
      - MODULE=notifier
      - DOMAIN
      - PROTOCOL
    deploy:
      << : *local-placement
      mode: global

  notifier_en:
    << : *app-default 
    image: pastvu/backend:${TAG_EN:?ERR}
    networks:
      - backend
    environment:
      - MODULE=notifier
      - LANG=en
      - DOMAIN
      - PROTOCOL
    deploy: 
      << : *local-placement
      mode: global

  uploader:
    << : *app-default
    deploy:
      << : *local-placement
      mode: global
    networks:
      - frontend
      - backend
    environment:
      - MODULE=uploader
    volumes:
      - store:/store

  downloader:
    << : *app-default
    deploy: *local-placement
    networks:
      - frontend
      - backend
    environment:
      - MODULE=downloader
    volumes:
      - store:/store:ro

  sitemap:
    << : *app-default
    deploy: *local-placement
    networks:
      - backend
    environment:
      - MODULE=sitemap
      - DOMAIN
      - PROTOCOL
    volumes:
      - sitemap:/sitemap

  api:
    << : *app-default
    networks:
      - backend

  mongo:
    deploy:
      << : *local-placement
      mode: global
    image: pastvu/mongo:3.2.22
    networks:
      - backend
    volumes:
      - mongo:/data/db

  redis:
    image: redis:6.2.6
    networks:
      - backend


networks:
  frontend:
  backend:

volumes:
  store:
  sitemap:
