version: '3.8'

x-defaults:
  &production-defaults
  logging:
    driver: local
    options:
      max-size: "100m"

services:

  fileserver:
    << : *production-defaults
    deploy:
      replicas: 3

  frontend_en:
    << : *production-defaults
    deploy:
      replicas: 3

  frontend_ru:
    << : *production-defaults
    deploy:
      replicas: 3

  mongo:
    << : *production-defaults

  app_ru:
    << : *production-defaults
    deploy:
      replicas: 3
    secrets:
      - smtp_host
      - smtp_user
      - smtp_pass
      - pastvu_yandex_api_key
      - pastvu_google_api_key

  app_en:
    << : *production-defaults
    deploy:
      replicas: 3    
    secrets:
      - smtp_host
      - smtp_user
      - smtp_pass
      - pastvu_yandex_api_key
      - pastvu_google_api_key

  api:
    << : *production-defaults
    deploy:
      replicas: 2

  uploader:
    << : *production-defaults

  downloader:
    << : *production-defaults
    deploy:
      replicas: 3

  worker:
    << : *production-defaults

  notifier_ru:
    << : *production-defaults
    secrets:
      - smtp_host
      - smtp_user
      - smtp_pass

  notifier_en:
    << : *production-defaults
    secrets:
      - smtp_host
      - smtp_user
      - smtp_pass

secrets:
  smtp_host:
    file: /etc/secrets/smtp_host
  smtp_user:
    file: /etc/secrets/smtp_user
  smtp_pass:
    file: /etc/secrets/smtp_pass
  pastvu_yandex_api_key:
    external: true
  pastvu_google_api_key:
    external: true
